# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# in _config.yml

title: Optimization of pump operation under transients in hydraulic turbine rigs
author: wengang.mao@chalmers.se
logo: contents/images/turbine.png



# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force